### ISSUE TITLE
Image width is set to "0" in previous builds

### ISSUE THREAD

**Issue by fdubuisson** [biouno/image-gallery-plugin#1]
Our configuration uses this plugin on archived artifacts. In the configuration, we don't define an image width.

In latest build, the images are displayed correctly (full size).
In previous builds, the images are not visible; inspecting the page source code shows that image width is set to "0".

```
<h2>Screenshots</h2>
<a href="artifact/reports/iPad/Test_AddFavoriteContact/20151030_161534.368//Screen_Error.jpeg" title="reports/iPad/Test_AddFavoriteContact/20151030_161534.368//Screen_Error.jpeg" class="gallery"><img src="artifact/reports/iPad/Test_AddFavoriteContact/20151030_161534.368//Screen_Error.jpeg" width="0" title="Image 0" /></a>
```

Changing the size in the source code (using Chrome inspector, for example) brings back the images.

Using plugin v1.2 on Jenkins v1.634, MacOS 10.10.5

**Comment by kinow** [comment]
Hi @fdubuisson, sorry, I hand't notice that this repository was open for issues/pull requests. The code has been migrated to Jenkins, and released to all the Jenkins users and community. 

Thus, the issues are now kept in https://issues.jenkins-ci.org/secure/Dashboard.jspa, under component image-gallery-plugin. Could you file this same issue there (copy/paste), or just let me know and I'll file it there and you can watch it.

Sorry for the trouble. I will start a new development cycle for all BioUno plug-ins in the next days, and will make sure to release a new version of image-gallery-plugin in case we have fixed this issue :-)

Thanks.
Bruno

**Comment by fdubuisson** [comment]
Hi Bruno,

thanks for your quick reply!
Here is the Jira ticket: https://issues.jenkins-ci.org/browse/JENKINS-31364

Best regards,
Frederic


2015-11-03 1:25 GMT+01:00 Bruno P. Kinoshita <notifications@github.com>:

> Hi @fdubuisson <https://github.com/fdubuisson>, sorry, I hand't notice
> that this repository was open for issues/pull requests. The code has been
> migrated to Jenkins, and released to all the Jenkins users and community.
>
> Thus, the issues are now kept in
> https://issues.jenkins-ci.org/secure/Dashboard.jspa, under component
> image-gallery-plugin. Could you file this same issue there (copy/paste), or
> just let me know and I'll file it there and you can watch it.
>
> Sorry for the trouble. I will start a new development cycle for all BioUno
> plug-ins in the next days, and will make sure to release a new version of
> image-gallery-plugin in case we have fixed this issue :-)
>
> Thanks.
> Bruno
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biouno/image-gallery-plugin/issues/1#issuecomment-153202653>
> .
>



-- 
Frédéric Dubuisson
BeTomorrow
+33557590625

**Comment by kinow** [comment]
Oh, I thank you! Will close this issue and disable issues - which will probably make this issue be not visible anymore.
